# Generated by Django 4.2.16 on 2024-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
