# Generated by Django 4.2.16 on 2024-11-24 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='guest_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La capacidad de huéspedes debe ser mayor que 0'), django.core.validators.MaxValueValidator(30, message='La capacidad de huéspedes no puede ser mayor que 30')]),
        ),
    ]
