# Generated by Django 4.2.16 on 2024-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apartment_guest_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='can_cancel',
        ),
    ]
