# Generated by Django 5.1.1 on 2024-11-11 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apartmentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='guest_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
