# Generated by Django 4.2.16 on 2024-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_reservation_can_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='can_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
