# Generated by Django 5.1.1 on 2024-11-11 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apartment_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='guest_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La capacidad de huéspedes debe ser mayor que 0')]),
        ),
    ]
